# Generated by Django 2.2 on 2020-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
