# Generated by Django 2.2 on 2020-04-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_auto_20200405_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.UserAccount'),
        ),
    ]
