# Generated by Django 2.2 on 2020-04-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_auto_20200407_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account_app.UserAccount'),
        ),
    ]
