# Generated by Django 2.2 on 2020-04-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('chatbot_app', '0008_remove_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account_app.UserAccount'),
        ),
    ]
