# Generated by Django 2.2 on 2020-04-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_chat_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='username',
            new_name='name',
        ),
    ]
