# Generated by Django 2.2 on 2020-04-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_auto_20200407_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.UserAccount'),
        ),
    ]
